name: Firebase Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Python Dependency
        run: |
          cd functions && python3 -m venv venv
          . venv/bin/activate && pip install -r requirements.txt -q

      - name: Set Firebase Credential
        run: echo "${GOOGLE_APPLICATION_CREDENTIALS}" > ./cred.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
      - name: Deploy Firebase Functions
        run: firebase deploy --only functions:runner
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "cred.json"
